name: CI

on:
  push:
    branches: [ "trafego-master" ]
  pull_request:
    branches: [ "trafego-master" ]

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        working-directory: ./estagios-saude/api
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
      - name: Run tests
        working-directory: ./estagios-saude/api
        run: |
          source venv/bin/activate
          pytest -q
